comment:
  behavior: default
  layout: reach, diff, flags, files
  require_base: false
  require_changes: true
  require_head: true
coverage:
  status:
    project:
      default:
        base: auto
        flags:
        - unit
        paths:
        - ^src.*
        target: auto
        threshold: 0.0

