using NUnit.Framework;
using System.Collections.Generic;
using TopDownProteomics.Proteomics;

namespace TopDownProteomics.Tests
{
    [TestFixture]
    public static class ProteoformClassifierTest
    {
        [Test]
        public static void TestProteoformClassification()
        {
            //Test classifier
            List<string> lines = new List<string>
            {
                "Scan Number,Full Sequence,Gene Name",
                "2,MPWRAGNGVGLEAQAGTQEAGPEEYCQEELGAEEEMAARAAWPVLRSVNSRELSRIIICNHSPRIVLPVWLNYYGKLLPYLTLLPGRDFRIHNFRSHPWLFRDARTHDKLLVNQTELFVPSSNVNGQPVFANITLQCIP,primary:VHLL",
                "4,MKSDYVAVGM[Common Variable: Oxidation on M]MLSQTVVGVLGSFSVLLHYLSFYCTGCRLRSTDLIVKHLIVANFLALRCKGVPQTIAAFGVRYFLNALGCKLVFYLHRVGRGVSIGTTCLLSVFQVITVSSRKSRWAKLKEKAPKHVGFSVLLCWIVCMLVNIIFPMYVTGKWNYTNITVNEDLGYCSGGGNNKIAQTLR|MKSDYVAVGMM[Common Variable: Oxidation on M]LSQTVVGVLGSFSVLLHYLSFYCTGCRLRSTDLIVKHLIVANFLALRCKGVPQTIAAFGVRYFLNALGCKLVFYLHRVGRGVSIGTTCLLSVFQVITVSSRKSRWAKLKEKAPKHVGFSVLLCWIVCMLVNIIFPMYVTGKWNYTNITVNEDLGYCSGGGNNKIAQTLR,primary:VN1R4",
                "6,K[Common Biological: Acetylation on K]SDYVAVGMMLSQTVVGVLGSFSVLLHYLSFYCTGCRLRSTDLIVKHLIVANFLALRCKGVPQTIAAFGVRYFLNALGCKLVFYLHRVGRGVSIGTTCLLSVFQVITVSSRKSRWAKLKEKAPKHVGFSVLLCWIVCMLVNIIFPMYVTGKWNYTNITVNEDLGYCSGGGNNKIAQTLR|K[Common Biological: Trimethylation on K]SDYVAVGMMLSQTVVGVLGSFSVLLHYLSFYCTGCRLRSTDLIVKHLIVANFLALRCKGVPQTIAAFGVRYFLNALGCKLVFYLHRVGRGVSIGTTCLLSVFQVITVSSRKSRWAKLKEKAPKHVGFSVLLCWIVCMLVNIIFPMYVTGKWNYTNITVNEDLGYCSGGGNNKIAQTLR,primary:VN1R4",
                "8,MADEALFLLLHNEMVSGVYKSAEQGEVENGRCITKLENMGFRVGQGLIERFTKDTARFKDELDIMKFICKDFWTTVFKKQIDNLRTNHQGIYVLQDNKFRLLTQMSAGKQYLEHASKYLAFTCGLIRGGLSNLGIKSIVTAEVSSMPACKFQVMIQKI|MADEALFLLLHNEMVSGVYKSAEQGEVENGRCITKLENMGFRVGQGLIERFTKDTARFKDELDIMKFICKDFWTTVFKKQIDNLRTNHQGIYVLQDNKFRLLTQMSAGKQYLEHASKYLAFTCGLIRGGLSNLGIKSIVTAEVSSMPACKFQVMIQKL,primary:TRAPPC6B",
                "10,MEEAGLCGLREKADMLCNSESHDILQHQDSNCSATSNKHLLEDEEGRDFITKNRSWVSPVHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKKYADLGNSPLL,primary:TXLNGY|primary:TXLNGZ",
                "12,MEEAGLCGLREKADMLCNSESHDILQHQDSNCSATSNKHLLEDEEGRDFITKNRSWVSPVHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKK[Common Biological: Acetylation on K]YADLGNSPLL|MEEAGLCGLREKADMLCNSESHDILQHQDSNCSATSNKHLLEDEEGRDFITKNRSWVSPVHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKK[Common Biological: Acetylation on K]YADLGNSPLL|MEEAGLCGLREKADMLCNSESHDILQHQDSNCSATSNKHLLEDEEGRDFITKNRSWVSPVHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKK[Common Biological: Trimethylation on K]YADLGNSPLL|MEEAGLCGLREKADMLCNSESHDILQHQDSNCSATSNKHLLEDEEGRDFITKNRSWVSPVHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKK[Common Biological: Trimethylation on K]YADLGNSPLL,primary:TXLNGY|primary:TXLNGZ|primary:TXLNGY|primary:TXLNGZ",
                "14,MEEAGLCGLREKADMLCNSESHDILQHQDSNCSATSNK[Common Biological: Acetylation on K]HLLEDEEGRDFITKNRSWVSPVHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKKYADLGNSPLL|MEEAGLCGLREKADMLCNSESHDILQHQDSNCSATSNK[Common Biological: Acetylation on K]HLLEDEEGRDFITKNRSWVSPVHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKKYADLGNSPLL|MEEAGLCGLREKADMLCNSESHDILQHQDSNCSATSNK[Common Biological: Trimethylation on K]HLLEDEEGRDFITKNRSWVSPVHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKKYADLGNSPLL|MEEAGLCGLREKADMLCNSESHDILQHQDSNCSATSNK[Common Biological: Trimethylation on K]HLLEDEEGRDFITKNRSWVSPVHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKKYADLGNSPLL|MEEAGLCGLREKADMLCNSESHDILQHQDSNCSATSNKHLLEDEEGRDFITK[Common Biological: Acetylation on K]NRSWVSPVHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKKYADLGNSPLL|MEEAGLCGLREKADMLCNSESHDILQHQDSNCSATSNKHLLEDEEGRDFITK[Common Biological: Acetylation on K]NRSWVSPVHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKKYADLGNSPLL|MEEAGLCGLREKADMLCNSESHDILQHQDSNCSATSNKHLLEDEEGRDFITK[Common Biological: Trimethylation on K]NRSWVSPVHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKKYADLGNSPLL|MEEAGLCGLREKADMLCNSESHDILQHQDSNCSATSNKHLLEDEEGRDFITK[Common Biological: Trimethylation on K]NRSWVSPVHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKKYADLGNSPLL,primary:TXLNGY|primary:TXLNGZ|primary:TXLNGY|primary:TXLNGZ|primary:TXLNGY|primary:TXLNGZ|primary:TXLNGY|primary:TXLNGZ",
                "16,M[Common Variable: Oxidation on M]EEAGLCGLREKADMLCNSESHDILQHQDSNCSATSNKHLLEDEEGRDFITKNRSWAAAAHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKKYADLGNSPLL|MEESGLCGLREKADMLCNSESHDILQHQDSNCSATSNKHLLEDEEGRDFITKNRSWAAAAHCTQESRRELPEQEVAPPSGQQALQCNRNKEKVLGKEVLLLMQALNTLSTPEEKLAALCKKYADLGNSPLL,primary:TXLNGW|primary:TXLNGX",
                "18,MABSDX,primary:TXLNGA",
                "20,MACDEGM[+16]ASDF,primary:TXLNGB"
            };

            List<string> expectedLevels = new List<string> { "1", "2A", "2B", "2C", "2D", "3", "4", "5", "2C", "2B", "2B" }; //each of these should be identified in the vignette

            //iterate through each result, check if there's a header or not
            for (int i = 1; i < lines.Count; i++)
            {
                string[] line = lines[i].Split(',');
                //should be scan number, sequence(s), gene(s)
                string level = FiveLevelProteoformClassifier.ClassifyPrSM(line[1], line[2]);

                Assert.AreEqual(level, expectedLevels[i - 1]);
            }
        }
    }
}
