name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Add msbuild
      run: dotnet add tests/TopDownProteomics.Tests/TopDownProteomics.Tests.csproj package coverlet.msbuild
    - name: Test
      run:
        dotnet test --no-build --verbosity normal
          /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
          /p:CoverletOutput='../../coverage.xml'
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        verbose: true
        files: ./coverage.xml
